document.addEventListener("DOMContentLoaded",function(){if(typeof AOS!=="undefined"){AOS.init({once:!0})}else{console.error("مكتبة AOS لم يتم تحميلها بشكل صحيح.")}
disableScroll();window.addEventListener("load",function(){let preloader=document.getElementById("preloader");if(preloader){preloader.classList.add("preloader-hidden");setTimeout(()=>{preloader.style.display="none";enableScroll()},600)}})});function disableScroll(){document.body.classList.add("no-scroll")}
function enableScroll(){document.body.classList.remove("no-scroll")}
function makeDraggable(box){let isDragging=!1,offsetX,offsetY,posX=0,posY=0;box.addEventListener("mousedown",(e)=>{isDragging=!0;offsetX=e.clientX-posX;offsetY=e.clientY-posY;box.style.cursor="grabbing"});document.addEventListener("mousemove",(e)=>{if(isDragging){posX=e.clientX-offsetX;posY=e.clientY-offsetY;box.style.transform=`translate(${posX}px, ${posY}px)`}});document.addEventListener("mouseup",()=>{isDragging=!1;box.style.cursor="grab"})}
function timeSinceUpdate(lastUpdate){let lastUpdateDate=new Date(lastUpdate);let now=new Date();let diffMs=now-lastUpdateDate;let diffSeconds=Math.floor(diffMs/1000);let diffMinutes=Math.floor(diffSeconds/60)%60;let diffHours=Math.floor(diffSeconds/3600)%24;let diffDays=Math.floor(diffSeconds/(3600*24));let diffWeeks=Math.floor(diffDays/7);let diffMonths=Math.floor(diffDays/30);function getPluralForm(value,singular,dual,plural){if(value===1)return singular;if(value===2)return dual;return plural}
let parts=[];if(diffMonths>0){parts.push(`${diffMonths} ${getPluralForm(diffMonths, "شهر", "شهرين", "أشهر")}`)}else if(diffWeeks>0){parts.push(`${diffWeeks} ${getPluralForm(diffWeeks, "أسبوع", "أسبوعين", "أسابيع")}`)}else if(diffDays>0){parts.push(`${diffDays} ${getPluralForm(diffDays, "يوم", "يومين", "أيام")}`)}else{if(diffHours>0){parts.push(`${diffHours} ${getPluralForm(diffHours, "ساعة", "ساعتين", "ساعات")}`)}
if(diffMinutes>0){parts.push(`${diffMinutes} ${getPluralForm(diffMinutes, "دقيقة", "دقيقتين", "دقائق")}`)}}
if(parts.length===0){parts.push(`${diffSeconds} ${getPluralForm(diffSeconds, "ثانية", "ثانيتين", "ثوانٍ")}`)}
return parts.join(" و ")}
function fetchUpdateDetails(){fetch("../update_log.json").then(response=>response.json()).then(data=>{let updateHTML=`<div class="update_line">   <span class="variable update_margin1">webStart</span>: <span class="string">"${data.datee}"</span>,<br></div>`;updateHTML+=` <div class="update_line">  <span class="variable update_margin1">lastUpdate</span>: <span class="string" dir="rtl">"${timeSinceUpdate(data.lastUpdate)}"</span>,<br></div>`;if(data.newFeatures.length>0){updateHTML+=` <div class="update_line"> <span class="variable update_margin1">newFeatures</span>: <span class="bracket">[</span></div>`;data.newFeatures.forEach(feature=>{updateHTML+=`  <div class="update_line">  <span class="string update_margin2">"${feature}"</span>,</div>`});updateHTML+=` <div class="update_line"> <span class="bracket">]</span>,</div>`}
if(data.bugFixes.length>0){updateHTML+=` <div class="update_line"><span class="variable update_margin1">bugFixes</span>: <span class="bracket">[</span></div>`;data.bugFixes.forEach(fix=>{updateHTML+=`   <div class="update_line"> <span class="string update_margin2">"${fix}"</span>,</div>`});updateHTML+=`  <div class="update_line"><span class="bracket">]</span></div>`}
updateHTML+=``;document.getElementById("update-details").innerHTML=updateHTML}).catch(()=>{document.getElementById("update-details").textContent="⚠️ فشل تحميل التحديثات!"})}
fetchUpdateDetails();'use strict';const elementToggleFunc=(elem)=>elem.classList.toggle("active");const sidebar=document.querySelector("[data-sidebar]");const sidebarBtn=document.querySelector("[data-sidebar-btn]");if(sidebar&&sidebarBtn){sidebarBtn.addEventListener("click",()=>elementToggleFunc(sidebar))}
const select=document.querySelector('[data-select]');const selectItems=document.querySelectorAll('[data-select-item]');const selectValue=document.querySelector('[data-select-value]');const filterBtn=document.querySelectorAll('[data-filter-btn]');const filterItems=document.querySelectorAll('[data-filter-item]');const filterFunc=(selectedValue)=>{filterItems.forEach(item=>{const category=item.dataset.category||"";if(selectedValue==="all"||category===selectedValue){item.classList.add('active');item.style.display="block"}else{item.classList.remove('active');item.style.display="none"}})};if(select&&selectValue){select.addEventListener('click',()=>elementToggleFunc(select));selectItems.forEach(item=>{item.addEventListener('click',function(){const selectedValue=this.innerText.trim().toLowerCase();selectValue.innerText=this.innerText;elementToggleFunc(select);filterFunc(selectedValue)})})}
let lastClickedBtn=filterBtn.length?filterBtn[0]:null;filterBtn.forEach(btn=>{btn.addEventListener('click',function(){const selectedValue=this.innerText.trim().toLowerCase();selectValue.innerText=this.innerText;filterFunc(selectedValue);if(lastClickedBtn)lastClickedBtn.classList.remove('active');this.classList.add('active');lastClickedBtn=this})});const form=document.querySelector('[data-form]');const formInputs=document.querySelectorAll('[data-form-input]');const formBtn=document.querySelector('[data-form-btn]');if(form&&formBtn){formInputs.forEach(input=>{input.addEventListener('input',function(){formBtn.disabled=!form.checkValidity()})})}
const navigationLinks=document.querySelectorAll('[data-nav-link]');const pages=document.querySelectorAll('[data-page]');const secretButton=document.querySelector('[data-secret-nav]');let secretClickCount=0;const clickSound=new Audio('../sound/note.mp3');const successSound=new Audio('../sound/complet.mp3');navigationLinks.forEach(link=>{link.addEventListener('click',function(){let targetPage=this.dataset.target||this.innerText.trim().toLowerCase();if(this.hasAttribute('data-secret-nav')){secretClickCount++;if(secretClickCount<7){clickSound.play()}else{successSound.play();activatePage(targetPage,this)}}else{activatePage(targetPage,this)}})});function activatePage(targetPage,clickedElement){pages.forEach(page=>{page.classList.toggle('active',page.dataset.page===targetPage)});navigationLinks.forEach(nav=>nav.classList.remove('active'));clickedElement.classList.add('active');window.scrollTo(0,0)}
document.querySelectorAll('#back-to-home').forEach(button=>{button.addEventListener('click',function(event){event.preventDefault();const homeNav=[...navigationLinks].find(nav=>nav.innerText.trim()==="الرئيسية");if(homeNav){homeNav.click();setTimeout(()=>{const mapElement=document.getElementById('map');if(mapElement){mapElement.scrollIntoView({behavior:'smooth',block:'start'})}},100)}})});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".laung").forEach(laung=>{const label=document.createElement("div");label.className="svg-label";label.textContent=laung.getAttribute("data-label");laung.appendChild(label);laung.addEventListener("click",function(){document.querySelectorAll(".svg-label").forEach(lbl=>lbl.style.display="none");label.style.display="block"})});document.addEventListener("click",function(event){if(!event.target.closest(".laung")){document.querySelectorAll(".svg-label").forEach(lbl=>lbl.style.display="none")}})});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".date").forEach(element=>{const dataDate=element.getAttribute("data-date");const date=new Date(dataDate);const now=new Date();const diff=now-date;const days=Math.floor(diff/86400000);const weeks=Math.floor(days/7);const months=Math.floor(days/30);let message="";if(days<1){const hours=Math.floor(diff/3600000);message=hours<1?`قبل ${Math.floor(diff / 60000)} دقيقة`:`قبل ${hours} ساعة`}else if(days<=6){message=`قبل ${days} ${days === 1 ? "يوم" : "أيام"}`}else if(weeks<=4){message=`قبل ${weeks} ${weeks === 1 ? "أسبوع" : "أسابيع"}`}else{message=`قبل ${months} ${months === 1 ? "شهر" : "أشهر"}`}
element.textContent=message})});const soundButton=document.getElementById("sound-toggle");const themeButton=document.getElementById("theme-toggle");soundButton.checked=localStorage.getItem("sound")==="enable";themeButton.checked=localStorage.getItem("theme")==="light";const body=document.body;let soundEnabled=localStorage.getItem("sound")==="enable";const audioContext=new(window.AudioContext||window.webkitAudioContext)();function playSound(file){if(audioContext.state==="suspended"){audioContext.resume().then(()=>{console.log("تم استئناف AudioContext.")})}
const audio=new Audio(`../sound/${file}`);audio.play().catch(error=>console.error("خطأ في تشغيل الصوت:",error))}
if(localStorage.getItem("sound")===null){soundEnabled=!0;localStorage.setItem("sound","enable")}
let theme=localStorage.getItem("theme")||"dark";body.classList.toggle("light-mode",theme==="light");function updateButtons(){if(soundButton){soundButton.textContent=soundEnabled?"🔊 صوت مفعل":"🔇 صوت معطل"}
if(themeButton){themeButton.textContent=theme==="dark"?"🌙 الوضع الداكن":"☀️ الوضع الفاتح"}}
updateButtons();document.addEventListener("click",(event)=>{if(audioContext.state==="suspended"){audioContext.resume()}
if(!soundEnabled)return;const soundFile=event.target.getAttribute("data-sound");if(soundFile){playSound(soundFile)}});if(themeButton){themeButton.addEventListener("click",()=>{playSound(theme==="dark"?"light_on.wav":"light_on.wav");theme=theme==="dark"?"light":"dark";body.classList.toggle("light-mode",theme==="light");localStorage.setItem("theme",theme);updateButtons()})}
if(soundButton){soundButton.addEventListener("click",()=>{soundEnabled=!soundEnabled;localStorage.setItem("sound",soundEnabled?"enable":"disable");updateButtons();playSound(soundEnabled?"enable.mp3":"disable.mp3")})}
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(40,window.innerWidth/window.innerHeight,0.1,9);const renderer=new THREE.WebGLRenderer({canvas:document.getElementById('bg'),alpha:!0});renderer.setSize(window.innerWidth,window.innerHeight);camera.position.z=5;const geometry=new THREE.BoxGeometry(1,1,1);const material=new THREE.MeshBasicMaterial({color:0x00ffff,wireframe:!0});const cube=new THREE.Mesh(geometry,material);scene.add(cube);function animate(){requestAnimationFrame(animate);cube.rotation.x+=0.01;cube.rotation.y+=0.01;renderer.render(scene,camera)}
animate();document.getElementById("shakeButton").addEventListener("click",function(){let button=this;button.classList.add("shake");setTimeout(()=>{button.classList.remove("shake")},300)});if(navigator.userAgent.includes("Instagram")){alert("قد تواجه مشاكل في عرض الموقع داخل متصفح Instagram. يُفضل فتحه في متصفح خارجي.")}
function showAlert(message,type='info',duration=3000){const alertsContainer=document.getElementById('alerts-container');const alertDiv=document.createElement('div');alertDiv.className=`alert ${type}`;alertDiv.innerHTML=`
        <span>${message}</span>
        <span class="close-btn">&times;</span>
    `;alertsContainer.appendChild(alertDiv);alertDiv.querySelector('.close-btn').addEventListener('click',()=>{alertDiv.style.opacity='0';setTimeout(()=>alertDiv.remove(),500)});setTimeout(()=>{alertDiv.style.opacity='0';setTimeout(()=>alertDiv.remove(),500)},duration)}
function clearForm(formId){document.querySelector(`#${formId} input[name="username"]`).value='';document.querySelector(`#${formId} textarea[name="message"]`).value='';if(formId==='contactForm1'){document.querySelector(`#${formId} input[type="file"]`).value='';document.getElementById('file-name1').textContent='تحميل ملف';document.getElementById('image-name1').textContent='تحميل صورة'}}
async function getIPAddress(){try{const response=await fetch('https://api.ipify.org?format=json');const data=await response.json();return data.ip}catch(error){console.error('Error fetching IP address:',error);return'غير متوفر'}}
document.getElementById('contactForm1').addEventListener('submit',async function(event){event.preventDefault();const username=document.getElementById('username1').value.trim();const message=document.getElementById('message1').value.trim();const fileInput=document.getElementById('file1');const imageInput=document.getElementById('image1');const file=fileInput.files.length>0?fileInput.files[0]:null;const image=imageInput.files.length>0?imageInput.files[0]:null;const ipAddress=await getIPAddress();if(!username||!message){showAlert("❌ يرجى ملء جميع الحقول!","error");return}
let endpoint="sendMessage";let url=`https://api.telegram.org/bot7741815017:AAGTPiZID3RsHP-H9N67NVXKlrTygrMh-VY/${endpoint}`;let formData;if(file){endpoint="sendDocument";url=`https://api.telegram.org/bot7741815017:AAGTPiZID3RsHP-H9N67NVXKlrTygrMh-VY/${endpoint}`;formData=new FormData();formData.append('chat_id',5962064921);formData.append('caption',`👤 الاسم: ${username}\n💬 الرسالة: ${message}\n🌐 IP: ${ipAddress}`);formData.append('document',file)}else if(image){endpoint="sendPhoto";url=`https://api.telegram.org/bot7741815017:AAGTPiZID3RsHP-H9N67NVXKlrTygrMh-VY/${endpoint}`;formData=new FormData();formData.append('chat_id',5962064921);formData.append('caption',`👤 الاسم: ${username}\n💬 الرسالة: ${message}\n🌐 IP: ${ipAddress}`);formData.append('photo',image)}else{formData=JSON.stringify({chat_id:5962064921,text:`👤 الاسم: ${username}\n💬 الرسالة: ${message}\n🌐 IP: ${ipAddress}`})}
try{const response=await fetch(url,{method:"POST",body:formData,headers:file||image?{}:{"Content-Type":"application/json"}});const data=await response.json();console.log("📨 Telegram Response:",data);if(data.ok){showAlert("✅ تم إرسال البلاغ بنجاح!","success");clearForm("contactForm1")}else{showAlert(`❌ فشل الإرسال: ${data.description || "خطأ غير معروف"}`,"error")}}catch(error){console.error("❌ خطأ أثناء الإرسال:",error);showAlert("❌ حدث خطأ أثناء الإرسال!","error")}});document.getElementById('messageForm').addEventListener('submit',async function(event){event.preventDefault();const statusMessage=document.getElementById('status-message');statusMessage.textContent="🚀 جاري الإرسال...";statusMessage.style.color="blue";const fullName=document.getElementById('fullName').value.trim();const userMessage=document.getElementById('userMessage').value.trim();if(!fullName||!userMessage){statusMessage.textContent="❌ يرجى ملء جميع الحقول!";statusMessage.style.color="red";return}
const ipAddress=await getIPAddress();const botToken="8182375548:AAEwMmAtlekkMM_12SerT66cc4e2DxJJv3g";const chatID=5962064921;const url=`https://api.telegram.org/bot${botToken}/sendMessage`;try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatID,text:`👤 الاسم: ${fullName}\n💬 الرسالة: ${userMessage}\n🌐 IP: ${ipAddress}`})});const data=await response.json();console.log("📨 Telegram Response:",data);if(data.ok){statusMessage.textContent="✅ تم إرسال الرسالة بنجاح!";statusMessage.style.color="green";document.getElementById('messageForm').reset()}else{statusMessage.textContent="❌ فشل في الإرسال: "+(data.description||"خطأ غير معروف");statusMessage.style.color="red"}}catch(error){console.error("❌ Error:",error);statusMessage.textContent="❌ حدث خطأ أثناء الإرسال!";statusMessage.style.color="red"}});async function getIPAddress(){try{const res=await fetch('https://api64.ipify.org?format=json');const data=await res.json();return data.ip}catch(error){console.error("❌ Error fetching IP:",error);return"غير معروف"}}
function showAlert(message,type){alert(message)}
document.getElementById("poetryAdviceForm").addEventListener("submit",function(event){event.preventDefault();let name=document.getElementById("poetryName").value||"مجهول";let message=document.getElementById("poetryMessage").value;let statusMessage=document.getElementById("poetryStatusMessage");let botToken="7952561228:AAH5t_OgXBnyZ9Pi3zRXNPNuuGeLU4AtmjM";let chatId="5962064921";let text=`📩 *رسالة جديدة حول قصائدي*\n\n👤 *المرسل:* ${name}\n📝 *الرسالة:* ${message}`;let url=`https://api.telegram.org/bot${botToken}/sendMessage?chat_id=${chatId}&text=${encodeURIComponent(text)}&parse_mode=Markdown`;statusMessage.textContent="📨 جاري الإرسال...";statusMessage.className="sending";fetch(url).then(response=>response.json()).then(data=>{if(data.ok){statusMessage.textContent="✅ تم إرسال رسالتك بنجاح!";statusMessage.className="success";document.getElementById("poetryAdviceForm").reset()}else{statusMessage.textContent="❌ فشل الإرسال، حاول مجددًا.";statusMessage.className="error"}}).catch(error=>{statusMessage.textContent="❌ تعذر الاتصال بالخادم.";statusMessage.className="error"})})